Traceback (most recent call last):
  File "/home/ndtorres/project/bwamin/bwamin.py", line 84, in <module>
    faOut = Fasta(faFile)
  File "/home/ndtorres/.local/lib/python3.9/site-packages/pyfaidx/__init__.py", line 1096, in __init__
    self.faidx = Faidx(
  File "/home/ndtorres/.local/lib/python3.9/site-packages/pyfaidx/__init__.py", line 511, in __init__
    self.build_index()
  File "/home/ndtorres/.local/lib/python3.9/site-packages/pyfaidx/__init__.py", line 691, in build_index
    raise e
  File "/home/ndtorres/.local/lib/python3.9/site-packages/pyfaidx/__init__.py", line 660, in build_index
    raise FastaIndexingError(
pyfaidx.FastaIndexingError: The FASTA file benchmark/ecoli/ERR10419847.fasta.small.fixed does not contain a valid sequence. Check that sequence definition lines start with '>'.
